import streamlit as st
from ui_components import render_header
import pandas as pd


def render(df: pd.DataFrame):
    render_header(
        "Data Quality, Exploratory Insights & Ethics",
        "Review dataset integrity checks, core exploratory findings, and model"
        " governance guidelines.",
    )

    tab1, tab2 = st.tabs(["📊 Data Health & EDA", "⚖️ AI Ethics & Governance"])

    with tab1:
        st.subheader("Dataset Integrity Auditing")
        if not df.empty:
            col1, col2 = st.columns(2)
            with col1:
                st.metric("Total Rows", f"{len(df):,}")
                st.metric(
                    "Missing Values Count", int(df.isnull().sum().sum())
                )
            with col2:
                st.metric("Total Columns", f"{df.shape[1]}")
                st.metric(
                    "Duplicate Rows", int(df.duplicated().sum())
                )

            st.markdown("#### Column Data Types & Non-Null Counts")
            buffer = io_buffer_info(df)
            st.dataframe(buffer, use_container_width=True)
        else:
            st.info("No dataset loaded.")

    with tab2:
        st.subheader("Responsible AI & Management Guardrails")
        st.info(
            "**Core Ethical Principle:** Predictions generated by Gheero PMS"
            " are strictly designed to support project management, enable"
            " early risk intervention, and optimize resource allocation—**never"
            " for employee evaluation, performance ranking, or punitive"
            " reviews.**"
        )
        st.markdown(
            """
            * **Transparency:** All risk flags provide SHAP explanation values to clarify why a task is flagged.
            * **Human-in-the-Loop:** Automated indicators require management confirmation before making structural workflow shifts.
            * **Fairness Audits:** Models are continuously monitored across departments to prevent systematic bias.
        """
        )


def io_buffer_info(df):
    import pandas as pd

    inf = pd.DataFrame(
        {
            "Column": df.columns,
            "Non-Null Count": df.notnull().sum().values,
            "Dtype": df.dtypes.astype(str).values,
        }
    )
    return inf